backend:
  name: github
  repo: vosaul/markus
media_folder: "images/icons"
public_folder: "images/icons"
publish_mode: editorial_workflow
collections:
  - label: "Main page (casinos list)"
    name: "mainpage"
    files:
      - name: "main"
        label: "Main page"
        file: "_data/main.yml"
        fields:
          - label: "title"
            name: 'title'
            widget: 'string'
            default: 'btc (BTC) Casinò italiani:'

          - label: 'casinos_header'
            name: 'casinos_header'
            widget: "list"

          - label: "casinos"
            name: "casinos"
            widget: "list"
            allow_add: true
            fields:
              - { label: "title", name: "title", widget: "string"}
              - { label: "order", name: "order", widget: "string", required: false}
              - { label: "link", name: "link", widget: "string", required: false}
              - { label: "icon", name: "icon", widget: "image"}
              - { label: "services", name: "services", widget: "string", required: false}
              - label: "languages"
                name: "languages"
                widget: "object"
                fields:
                  - {label: "icon", name: "icon", widget: "string", default: "times"}
                  - {label: "list", name: "list", widget: "string", required: false}
              - label: "support"
                name: "support"
                widget: "object"
                fields:
                  - {label: "icon", name: "icon", widget: "string", default: "times"}
                  - {label: "descr", name: "descr", widget: "string" , required: false}
              - label: "bcd_raiting"
                name: "bcd_raiting"
                widget: "object"
                fields:
                  - {label: "value", name: "value", widget: "number", valueType: "int", min: 1, max: 100}
                  - {label: "descr", name: "descr", widget: "string", required: false}
              - label: "max_bonus"
                name: "max_bonus"
                widget: "object"
                fields:
                  - {label: "value", name: "value", widget: "string", default: "1 BTC"}
                  - {label: "descr", name: "descr", widget: "string", required: false}
              - label: "provably_fair"
                name: "provably_fair"
                widget: "object"
                fields:
                  - {label: "icon", name: "icon", widget: "string", default: "thumbs-up"}
                  - {label: "descr", name: "descr", widget: "string", required: false}
              - label: "auszahlung"
                name: "u-auszahlung"
                widget: "object"
                fields:
                  - label: "currency"
                    name: "currency"
                    widget: "list"
                    fields:
                      - {label: "item", name: "item", widget: "string", default: "btc"}
                  - {label: "descr", name: "descr", widget: "string", required: false}

      - name: "review"
        label: "Reviews"
        folder: "/"
        file: "betcoin.md"
        media_folder: "images/icons"
        fields:
          - { label: "permalink", name: "permalink", widget: "string", default: "/", required: false}
          - { label: "slug", name: "slug", widget: "string"}
          - { label: "Layout", name: "layout", widget: "string", default: "casino" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime", required: false}
          - { label: "Body", name: "body", widget: "markdown" }
        slug: "{{slug}}"
      
  - name: "pages"
    label: "Pages"
    folder: "/"
    create: true
    media_folder: "images"
    fields:
      - { label: "permalink", name: "permalink", widget: "string", default: "/", required: false}
      - { label: "slug", name: "slug", widget: "string", required: false}
      - { label: "Layout", name: "layout", widget: "string", default: "casino" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", required: false}
      - { label: "Body", name: "body", widget: "markdown", required: false }
    slug: "{{slug}}"
  
